### ISSUE TITLE
Dataloader error

### ISSUE THREAD

**Issue by deeplearningdiaries** [ennauata/houseganpp#7]
Hi,

I am trying to reproduce the results of your paper and I am getting an error while loading data. The error is the following:

113 ./data/rplan/45776.json
[Epoch 0/200] [Batch 111/379] [D loss: 9.999077] [G loss: 81.515854] [L1 loss: 83.728096]
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    for i, batch in enumerate(fp_loader):
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
114 ./data/rplan/16164.json
    return self._process_data(data)
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 135, in __getitem__
    graph_nodes, graph_edges, rooms_mks = self.build_graph(rms_type, fp_eds, eds_to_rms)
  File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 294, in build_graph
    poly = self.make_sequence(np.array([fp_eds[l][:4] for l in eds_poly]))[0]
  File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 189, in make_sequence
    v_curr = tuple(edges[0][:2])
IndexError: index 0 is out of bounds for axis 0 with size 0

I have built the database with the repository [https://github.com/sepidsh/Housegan-data-reader](https://github.com/sepidsh/Housegan-data-reader)

I attach the file with the error, but I think that the error is not in the file but in the dataloader. When I feed just this file to the model, it works.
[16164.zip](https://github.com/ennauata/houseganpp/files/8402819/16164.zip)

Have you had this error before? Do you know how to solve it?

**Comment by sucream1004** [comment]
Hi,

I also encountered same error. Although I don't fully understand why, I resolved it by searching and removing the dataset which error occurs.

```
import json
import numpy as np
import os

def reader(filename):
	with open(filename) as f:
		info =json.load(f)
		rms_bbs=np.asarray(info['boxes'])
		fp_eds=info['edges']
		rms_type=info['room_type']
		eds_to_rms=info['ed_rm']
		s_r=0
		for rmk in range(len(rms_type)):
			if(rms_type[rmk]!=17):
				s_r=s_r+1	
		#print("eds_ro",eds_to_rms)
		rms_bbs = np.array(rms_bbs)/256.0
		fp_eds = np.array(fp_eds)/256.0 
		fp_eds = fp_eds[:, :4]
		tl = np.min(rms_bbs[:, :2], 0)
		br = np.max(rms_bbs[:, 2:], 0)
		shift = (tl+br)/2.0 - 0.5
		rms_bbs[:, :2] -= shift 
		rms_bbs[:, 2:] -= shift
		fp_eds[:, :2] -= shift
		fp_eds[:, 2:] -= shift 
		tl -= shift
		br -= shift
		eds_to_rms_tmp=[]
		for l in range(len(eds_to_rms)):
			eds_to_rms_tmp.append([eds_to_rms[l][0]])
		return rms_type,fp_eds,rms_bbs,eds_to_rms,eds_to_rms_tmp

file_list = glob('Housegan-data-reader/sample_output/*')

# with open('file_list.txt','r') as f:
#     lines = f.readlines()

lines = file_list

out_size = 64
length_edges = []
subgraphs = []
for line in lines:
    a=[]
    with open(line) as f2:
        rms_type, fp_eds,rms_bbs,eds_to_rms,eds_to_rms_tmp=reader(line) 

    eds_to_rms_tmp = []
    for l in range(len(eds_to_rms)):                  
        eds_to_rms_tmp.append([eds_to_rms[l][0]])

    rms_masks = []
    im_size = 256
    fp_mk = np.zeros((out_size, out_size))
    nodes = rms_type
    for k in range(len(nodes)):
        eds = []
        for l, e_map in enumerate(eds_to_rms_tmp):
            if (k in e_map):
                eds.append(l)
        b = []
        for eds_poly in [eds]:
            length_edges.append((line, np.array([fp_eds[l][:4] for l in eds_poly])))

chk = [x.shape for x in np.array(length_edges)[:,1]]
idx = [i for i,x in enumerate(chk) if len(x) != 2]
final = np.array(length_edges)[idx][:,0].tolist()
final = [x.replace('\n','') for x in final]

for fin in final:
    try:
        os.remove(fin)
    except:
        pass
```

**Comment by sucream1004** [comment]
I had the same error. In my case, when dataloader reads a file, the length of edges was weird. I tested with 16164.json that you uploaded, it looked fine. So I don't fully understand why.

Temporarily, I resolved it simply removed the json files that has an error when it's loaded.

**Comment by sakmalh** [comment]
Let me know if you found a solution for it @sucream1004 @deeplearningdiaries

**Comment by 1005wl** [comment]
> 我有同样的错误。就我而言，当数据加载器读取文件时，边缘的长度很奇怪。我用您上传的 16164.json 进行了测试，看起来不错。所以我不完全明白为什么。
> 
> 暂时，我解决了它只是删除了加载时出错的 json 文件。

请问已经解决了吗？

**Comment by 1005wl** [comment]
> 让我知道您是否找到了解决方案。

请问您解决这个问题了吗？

**Comment by 1005wl** [comment]
> Hi,
> 
> I am trying to reproduce the results of your paper and I am getting an error while loading data. The error is the following:
> 
> 113 ./data/rplan/45776.json [Epoch 0/200] [Batch 111/379] [D loss: 9.999077] [G loss: 81.515854] [L1 loss: 83.728096] Traceback (most recent call last): File "train.py", line 114, in for i, batch in enumerate(fp_loader): File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in **next** data = self._next_data() File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data 114 ./data/rplan/16164.json return self._process_data(data) File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data data.reraise() File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise raise exception IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/user/miniconda3/envs/houseganpp/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 135, in **getitem** graph_nodes, graph_edges, rooms_mks = self.build_graph(rms_type, fp_eds, eds_to_rms) File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 294, in build_graph poly = self.make_sequence(np.array([fp_eds[l][:4] for l in eds_poly]))[0] File "/home/user/houseganpp/dataset/floorplan_dataset_maps_functional_high_res.py", line 189, in make_sequence v_curr = tuple(edges[0][:2]) IndexError: index 0 is out of bounds for axis 0 with size 0
> 
> I have built the database with the repository https://github.com/sepidsh/Housegan-data-reader
> 
> I attach the file with the error, but I think that the error is not in the file but in the dataloader. When I feed just this file to the model, it works. [16164.zip](https://github.com/ennauata/houseganpp/files/8402819/16164.zip)
> 
> Have you had this error before? Do you know how to solve it?

"Have you already solved this issue? Looking forward to your reply."

**Comment by MalikHaroonKhokhar** [comment]
were you able to resolve it?

**Comment by MalikHaroonKhokhar** [comment]
Ended up resolving it by skipping the rooms with abnormal edges
