### ISSUE TITLE
Tensor Size Mismatch

### ISSUE THREAD

**Issue by sakmalh** [ennauata/houseganpp#9]
```
Traceback (most recent call last):
  File "/home/akmal/APIIT/FYP Code/houseganpp/train.py", line 194, in <module>
    visualizeSingleBatch(fp_loader_test, opt, exp_folder, batches_done)
  File "/home/akmal/APIIT/FYP Code/houseganpp/train.py", line 76, in visualizeSingleBatch
    gen_mks = generator(z, given_masks_in, given_nds, given_eds)
  File "/home/akmal/APIIT/FYP Code/houseganpp/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akmal/APIIT/FYP Code/houseganpp/models/models.py", line 156, in forward
    f = torch.cat([f, m], 1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 14 but got size 125 for tensor number 1 in the list.
```

**Comment by MalikHaroonKhokhar** [comment]
were you able to solve it?
